# File name: host_lambda.py
# Date: 10/6/26
# Author: Isaac Godfried. Coded originally by Claude Fable 5.1.
"""Turn a Colab training notebook into one that runs on a Lambda Cloud on-demand instance.

Colab terminated both v2.3a sessions ~8 h after allocation (2026-10-05/06) and spent hours "allocating"
an A100; a rented instance has no session cap and bills by the minute. The notebooks are Colab-specific
in exactly five lines (``google.colab.userdata`` for the two secrets, two ``/content`` paths, the ``%pip``
install), so the port is a set of asserted substitutions on a derived notebook plus:

* a one-time ``lambda_setup.sh`` that builds a venv with the **exact package versions the last Colab
  session ran with** (W&B run ``299r9bio``, ``requirements.txt``) and registers it as a Jupyter kernel, so
  the notebook's version gates keep their meaning;
* secrets read from the environment (headless ``nbconvert`` runs) or typed into a ``getpass`` prompt
  (interactive JupyterLab) — never stored in the notebook;
* the session time budget raised to a safety stop (``LAMBDA_TIME_BUDGET_H``): nothing ends a session but
  ``max_steps``;
* a wrap-up cell that marks the W&B run finished and says, loudly, to terminate the instance.

Data, schedule, checkpoint repo and the exact-resume machinery are untouched: a run started on Colab
resumes here from the Hub's ``last-checkpoint`` and could be resumed on Colab again.

Usage::

    .venv/bin/python -m src.finetuning.qwen_hebrew.colab.derive_v23a --revision <sha> --host lambda
"""
import copy
import re
from typing import Dict, List, Tuple

from src.finetuning.qwen_hebrew.colab.derive_v22b import _replace_line, _replace_once

LAMBDA_TIME_BUDGET_H = 48.0
WORK_DIR = "~/genizah_work"
VENV = "$HOME/genizah-venv"
KERNEL_NAME = "genizah"
SETUP_SCRIPT = "lambda_setup.sh"

#: Versions of the Colab session of 2026-10-05 (W&B run 299r9bio, requirements.txt), minus torch/torchvision
#: (installed from the PyTorch index matching the instance's driver) and xformers (its wheel is tied to one
#: torch/CUDA build; Unsloth falls back to SDPA attention without it).
PINS: Dict[str, str] = {
    "unsloth": "2026.8.9",
    "unsloth_zoo": "2026.8.6",
    "transformers": "4.57.6",
    "trl": "0.24.0",
    "peft": "0.21.1",
    "accelerate": "1.15.0",
    "bitsandbytes": "0.50.2",
    "datasets": "4.3.0",
    "tokenizers": "0.22.2",
    "safetensors": "0.8.0",
    "cut-cross-entropy": "25.1.1",
    "hf_transfer": "0.1.9",
    "huggingface_hub": "0.36.2",
    "wandb": "0.28.1",
    "pyarrow": "23.0.1",
    "pillow": "11.3.0",
    "sentencepiece": "0.2.2",
    "tyro": "1.0.16",
    "protobuf": "6.33.6",
}
TORCH_VERSION, TORCHVISION_VERSION = "2.11.0", "0.26.0"
PYTHON = "3.13"                                 # the Colab session ran 3.13.15
#: The pins the notebook's first cell asserts (the ones whose drift would change the training path).
KERNEL_GATE = ("unsloth", "unsloth_zoo", "transformers", "trl", "peft", "accelerate", "bitsandbytes")

LAUNCH_NOTES = """# {title} — **Lambda Cloud edition**

Derived from the Colab notebook by `host_lambda.py`: same data, schedule, checkpoint repo and exact resume.
It picks up a Colab-started run from the Hub's `last-checkpoint`, and Colab could resume it again.

**Instance:** 1× A100 40 GB (x86_64) is the proven configuration; 1× H100 PCIe runs ~1.5–2× faster for about
the same money per step. Not GH200 (ARM: the pinned wheels are untested there). Lambda Stack image, default disk.

**Once per instance** (JupyterLab → Terminal), after uploading this notebook and `{setup}` with the file browser:

```bash
bash {setup}
```

(~5 min: a venv with the exact package versions the last Colab session ran with, registered as the Jupyter
kernel **{kernel}**.)

**Run, interactive:** open this notebook, choose the kernel *genizah (venv)*, Run all. It asks for the Hugging
Face token (write access) and the W&B API key once; the browser tab can be closed, the kernel keeps running.

**Run, headless** (survives everything but the instance):

```bash
HF_TOKEN=… WANDB_API_KEY=… nohup {venv}/bin/jupyter nbconvert --to notebook --execute \\
  --ExecutePreprocessor.timeout=-1 --ExecutePreprocessor.kernel_name={kernel} \\
  {notebook} --output run1.ipynb > run1.log 2>&1 &
```

**When W&B shows the run finished: terminate the instance in the Lambda console — it bills by the minute.**

---

"""


def _setup_script() -> str:
    """The one-time environment script shipped next to the notebook.

    :return: Bash source.
    :rtype: str
    """
    pins = " ".join(f'"{name}=={ver}"' for name, ver in PINS.items())
    return f"""#!/bin/bash
# {SETUP_SCRIPT} — one-time environment for the Genizah fine-tune notebooks on a Lambda on-demand instance.
# Generated by src/finetuning/qwen_hebrew/colab/host_lambda.py: the pins are the versions the Colab session of
# 2026-10-05 (W&B run 299r9bio) ran with, so the notebook's version gates mean the same thing here.
# Usage (JupyterLab -> Terminal):   bash {SETUP_SCRIPT}      (about 5 minutes)
set -euo pipefail
VENV="{VENV}"
command -v nvidia-smi >/dev/null || {{ echo "nvidia-smi not found: this is not a GPU instance"; exit 1; }}
ARCH=$(uname -m)
[ "$ARCH" = "x86_64" ] || {{ echo "CPU architecture $ARCH is untested (GH200 is ARM): use an x86_64 instance"; exit 1; }}
DRIVER=$(nvidia-smi --query-gpu=driver_version --format=csv,noheader | head -1 | cut -d. -f1)
# torch wheels bundle their CUDA runtime; the driver decides which build can run (CUDA 13.0 needs driver >= 580)
if [ "$DRIVER" -ge 580 ]; then CUDA=cu130; else CUDA=cu128; fi
echo "driver $DRIVER -> torch {TORCH_VERSION}+$CUDA"
# uv brings its own Python {PYTHON} (the version the Colab session ran: every pin has wheels for it), whatever the image ships
command -v uv >/dev/null || curl -LsSf https://astral.sh/uv/install.sh | sh
export PATH="$HOME/.local/bin:$PATH"
uv venv --python {PYTHON} "$VENV"
uv pip install --python "$VENV/bin/python" --index-url "https://download.pytorch.org/whl/$CUDA" "torch=={TORCH_VERSION}" "torchvision=={TORCHVISION_VERSION}"
uv pip install --python "$VENV/bin/python" {pins} ipykernel nbconvert
"$VENV/bin/python" -m ipykernel install --user --name {KERNEL_NAME} --display-name "genizah (venv)"
"$VENV/bin/python" - <<'PY'
import torch, transformers, trl, peft, bitsandbytes, unsloth
p = torch.cuda.get_device_properties(0)
print(f"torch {{torch.__version__}} on {{p.name}} ({{p.total_memory / 2**30:.0f}} GiB); transformers {{transformers.__version__}}; "
      f"trl {{trl.__version__}}; peft {{peft.__version__}}; bitsandbytes {{bitsandbytes.__version__}}; unsloth {{unsloth.__version__}}")
PY
echo "kernel 'genizah (venv)' ready: open the notebook, choose that kernel, Run all"
"""


def setup_script() -> str:
    """Public accessor for the setup script text.

    :return: Bash source of ``lambda_setup.sh``.
    :rtype: str
    """
    return _setup_script()


def _content_leaf(src: str, name: str) -> str:
    """The path a Colab cell assigns under ``/content`` to ``name``.

    :param src: Cell source.
    :type src: str
    :param name: Variable name (``LOCAL`` or ``RESUME_ROOT``).
    :type name: str
    :return: The part after ``/content/``.
    :rtype: str
    :raises ValueError: When the cell has no such assignment.
    """
    m = re.search(rf'^{name} = "/content/(.+)"$', src, re.M)
    if not m:
        raise ValueError(f"{name} is not assigned under /content")
    return m.group(1)


def _install_cell(c1: str) -> str:
    """Replace the ``%pip`` install with the kernel version gate.

    :param c1: Source of the install cell.
    :type c1: str
    :return: Edited source.
    :rtype: str
    """
    gate = ("# Lambda: the kernel is the venv that lambda_setup.sh built with the Colab session's exact pins; nothing is installed here\n"
            "from importlib.metadata import version\n"
            "LAMBDA_KERNEL_PINS = " + repr({k: PINS[k] for k in KERNEL_GATE}) + "\n"
            "for _name, _ver in LAMBDA_KERNEL_PINS.items():\n"
            "    assert version(_name) == _ver, f\"{_name} drifted: {version(_name)} != {_ver} — run lambda_setup.sh and pick the 'genizah (venv)' kernel\"\n")
    c1 = _replace_line(c1, r'^%pip install -q "unsloth\[colab-new\]==.*$', gate.rstrip("\n"), "pip install")
    c1 = _replace_once(c1, 'assert torch.cuda.is_available(), "No GPU — switch runtime to A100"',
                       'assert torch.cuda.is_available(), "No GPU — this kernel does not see the instance\'s GPU"\n'
                       '_p = torch.cuda.get_device_properties(0)\n'
                       'print(f"GPU: {_p.name}, {_p.total_memory / 2**30:.0f} GiB")', "gpu check")
    return c1


def _data_cell(c2: str) -> str:
    """Secrets from the environment or a prompt; data under the work directory.

    :param c2: Source of the data cell.
    :type c2: str
    :return: Edited source.
    :rtype: str
    """
    c2 = _replace_once(c2, "import json\nfrom collections import Counter\n", "import json\nimport os\nfrom collections import Counter\nfrom getpass import getpass\n", "imports")
    c2 = _replace_line(c2, r"^from google\.colab import userdata$", "# secrets: HF_TOKEN / WANDB_API_KEY from the environment (headless), else typed into a prompt — never stored here", "userdata import")
    c2 = _replace_once(c2, 'login(token=userdata.get("HF_TOKEN"))',
                       'login(token=os.environ.get("HF_TOKEN") or getpass("Hugging Face token (write access): "))', "hf login")
    c2 = _replace_line(c2, r'^LOCAL = "/content/.+"$', f'LOCAL = os.path.expanduser("{WORK_DIR}/{_content_leaf(c2, "LOCAL")}")', "local data dir")
    return c2


def _helper_cell(c7: str) -> str:
    """Raise the session time budget to a safety stop.

    :param c7: Source of the helper cell.
    :type c7: str
    :return: Edited source.
    :rtype: str
    """
    return _replace_line(c7, r"^TIME_BUDGET_H = .*$",
                         f"TIME_BUDGET_H = {LAMBDA_TIME_BUDGET_H}   # Lambda: no session cap — a safety stop only; max_steps ends the run", "time budget")


def _train_cell(c8: str) -> str:
    """W&B key from the environment or a prompt; resume root under the work directory.

    :param c8: Source of the training cell.
    :type c8: str
    :return: Edited source.
    :rtype: str
    """
    c8 = _replace_once(c8, 'wandb.login(key=userdata.get("WANDB_API_KEY"))',
                       'import os\nfrom getpass import getpass\nwandb.login(key=os.environ.get("WANDB_API_KEY") or getpass("W&B API key: "))', "wandb login")
    c8 = _replace_line(c8, r'^RESUME_ROOT = "/content/.+"$', f'RESUME_ROOT = os.path.expanduser("{WORK_DIR}/{_content_leaf(c8, "RESUME_ROOT")}")', "resume root")
    return c8


def _wrapup_cell(run_name: str) -> Dict[str, object]:
    """The final cell: finish the W&B run and tell the operator to terminate the instance.

    :param run_name: W&B run name, for the alert title.
    :type run_name: str
    :return: A code cell.
    :rtype: Dict[str, object]
    """
    src = (f"# Wrap-up (Lambda): mark the W&B run finished, then TERMINATE THE INSTANCE in the Lambda console (it bills by the minute)\n"
           f"import wandb\n"
           f"if wandb.run is not None:\n"
           f"    wandb.alert(title=\"{run_name}: notebook finished\", text=\"training + merge done — terminate the Lambda instance\")   # e-mail if alerts are on in W&B settings\n"
           f"    wandb.finish()\n"
           f"print(\"=\" * 78)\n"
           f"print(\"DONE — TERMINATE THE INSTANCE IN THE LAMBDA CONSOLE NOW (it keeps billing until you do)\")\n"
           f"print(\"=\" * 78)\n")
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": src.splitlines(keepends=True)}


def _run_name(c8: str) -> str:
    """Read the W&B run name out of the training cell.

    :param c8: Source of the training cell.
    :type c8: str
    :return: The ``run_name`` value.
    :rtype: str
    :raises ValueError: When the cell has no ``run_name``.
    """
    m = re.search(r'run_name="([^"]+)"', c8)
    if not m:
        raise ValueError("training cell has no run_name")
    return m.group(1)


def to_lambda(nb: Dict, notebook_name: str) -> Dict:
    """Derive the Lambda edition of a Colab notebook.

    :param nb: A derived Colab notebook (``derive_v23a.derive`` output or the like).
    :type nb: Dict
    :param notebook_name: File name the edition will be written as (quoted in the launch notes).
    :type notebook_name: str
    :return: A new notebook; ``nb`` is not modified.
    :rtype: Dict
    :raises ValueError: When an expected Colab-specific line is missing (the substitutions are asserted).
    """
    out = copy.deepcopy(nb)
    cells = out["cells"]
    c0 = "".join(cells[0]["source"])
    title = c0.splitlines()[0].lstrip("# ").strip()
    cells[0]["source"] = (LAUNCH_NOTES.format(title=title, setup=SETUP_SCRIPT, kernel=KERNEL_NAME, venv=VENV, notebook=notebook_name) + c0).splitlines(keepends=True)
    cells[1]["source"] = _install_cell("".join(cells[1]["source"])).splitlines(keepends=True)
    cells[2]["source"] = _data_cell("".join(cells[2]["source"])).splitlines(keepends=True)
    cells[7]["source"] = _helper_cell("".join(cells[7]["source"])).splitlines(keepends=True)
    c8 = "".join(cells[8]["source"])
    cells[8]["source"] = _train_cell(c8).splitlines(keepends=True)
    cells.append(_wrapup_cell(_run_name(c8)))
    leftovers = [(i, line) for i, c in enumerate(cells) for line in "".join(c["source"]).splitlines()
                 if "google.colab" in line or "/content" in line or "userdata" in line]
    if leftovers:
        raise ValueError(f"Colab-specific lines remain: {leftovers}")
    return out


def lambda_files(colab_name: str) -> Tuple[str, str]:
    """File names of the Lambda edition and its setup script for a Colab notebook name.

    :param colab_name: e.g. ``genizah_v23a.ipynb``.
    :type colab_name: str
    :return: ``(notebook name, setup script name)``.
    :rtype: Tuple[str, str]
    """
    stem = colab_name[:-len(".ipynb")] if colab_name.endswith(".ipynb") else colab_name
    return f"{stem}_lambda.ipynb", SETUP_SCRIPT


def code_cells(nb: Dict) -> List[str]:
    """Sources of the code cells (for tests).

    :param nb: Notebook.
    :type nb: Dict
    :return: One string per code cell.
    :rtype: List[str]
    """
    return ["".join(c["source"]) for c in nb["cells"] if c["cell_type"] == "code"]
