#!/bin/bash
# lambda_setup.sh — one-time environment for the Genizah fine-tune notebooks on a Lambda on-demand instance.
# Generated by src/finetuning/qwen_hebrew/colab/host_lambda.py: the pins are the versions the Colab session of
# 2026-10-05 (W&B run 299r9bio) ran with, so the notebook's version gates mean the same thing here.
# Usage (JupyterLab -> Terminal):   bash lambda_setup.sh      (about 5 minutes)
set -euo pipefail
VENV="$HOME/genizah-venv"
command -v nvidia-smi >/dev/null || { echo "nvidia-smi not found: this is not a GPU instance"; exit 1; }
ARCH=$(uname -m)
[ "$ARCH" = "x86_64" ] || { echo "CPU architecture $ARCH is untested (GH200 is ARM): use an x86_64 instance"; exit 1; }
DRIVER=$(nvidia-smi --query-gpu=driver_version --format=csv,noheader | head -1 | cut -d. -f1)
# torch wheels bundle their CUDA runtime; the driver decides which build can run (CUDA 13.0 needs driver >= 580)
if [ "$DRIVER" -ge 580 ]; then CUDA=cu130; else CUDA=cu128; fi
echo "driver $DRIVER -> torch 2.11.0+$CUDA"
# uv brings its own Python 3.13 (the version the Colab session ran: every pin has wheels for it), whatever the image ships
command -v uv >/dev/null || curl -LsSf https://astral.sh/uv/install.sh | sh
export PATH="$HOME/.local/bin:$PATH"
uv venv --python 3.13 "$VENV"
uv pip install --python "$VENV/bin/python" --index-url "https://download.pytorch.org/whl/$CUDA" "torch==2.11.0" "torchvision==0.26.0"
uv pip install --python "$VENV/bin/python" "unsloth==2026.8.9" "unsloth_zoo==2026.8.6" "transformers==4.57.6" "trl==0.24.0" "peft==0.21.1" "accelerate==1.15.0" "bitsandbytes==0.50.2" "datasets==4.3.0" "tokenizers==0.22.2" "safetensors==0.8.0" "cut-cross-entropy==25.1.1" "hf_transfer==0.1.9" "huggingface_hub==0.36.2" "wandb==0.28.1" "pyarrow==23.0.1" "pillow==11.3.0" "sentencepiece==0.2.2" "tyro==1.0.16" "protobuf==6.33.6" ipykernel nbconvert
"$VENV/bin/python" -m ipykernel install --user --name genizah --display-name "genizah (venv)"
"$VENV/bin/python" - <<'PY'
import torch, transformers, trl, peft, bitsandbytes, unsloth
p = torch.cuda.get_device_properties(0)
print(f"torch {torch.__version__} on {p.name} ({p.total_memory / 2**30:.0f} GiB); transformers {transformers.__version__}; "
      f"trl {trl.__version__}; peft {peft.__version__}; bitsandbytes {bitsandbytes.__version__}; unsloth {unsloth.__version__}")
PY
echo "kernel 'genizah (venv)' ready: open the notebook, choose that kernel, Run all"
